# Generated by Django 4.1.5 on 2023-01-14 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="id",
            field=models.AutoField(max_length=11, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="menu",
            name="id",
            field=models.AutoField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
